export const USER_STATUS = {
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  SUSPENDED: 'Suspended',
  DELETED: 'Deleted',
};

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  USER_REGISTER: 'USER_REGISTER',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',
  USER_DELETE: 'USER_DELETE',
  USER_RESTORE: 'USER_RESTORE',
  USER_PERMANENT_DELETE: 'USER_PERMANENT_DELETE',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  AVATAR_UPDATE: 'AVATAR_UPDATE',
};

export const NOTIFICATION_EVENTS = {
  REGISTRATION: 'REGISTRATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  ROLE_CHANGE: 'ROLE_CHANGE',
  STATUS_CHANGE: 'STATUS_CHANGE',
};
